### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by petrkucerak** [petrkucerak/modlitbyzaulice#1]
- [x] animation of loading streets by the date of addition
- [x] #2
- [x] create a procedure for editing streets
- [x] create a script for generating cards
- [x] #5
- [x] #3
